### ISSUE TITLE
is `fwconsole r` command launched from wizard working?

### ISSUE THREAD

**Issue by Stell0** [nethesis/ns8-nethvoice#18]

**Comment by Stell0** [comment]
should be fixed with #20 https://github.com/nethesis/ns8-nethvoice/commit/cfb1ce3f49074e1581401c3c51129d50ef5362da

**Comment by Stell0** [comment]
nope still broken :(

**Comment by gsanchietti** [comment]
I've found also this issue (on Debian):
```
Error(s) have occured, the following is the retrieve_conf output:
exit: 1
Unable to continue. proc_open(/tmp/cron.error): failed to open stream: Permission denied in /var/www/html/freepbx/admin/libraries/BMO/Cron.class.php on line 281
#0 [internal function]: Whoops\Run->handleError(2, 'proc_open(/tmp/...', '/var/www/html/f...', 281, Array)
#1 /var/www/html/freepbx/admin/libraries/BMO/Cron.class.php(281): proc_open('/usr/bin/cronta...', Array, NULL)
#2 /var/www/html/freepbx/admin/libraries/BMO/Cron.class.php(162): FreePBX\Cron->installCrontab(Array)
#3 /var/lib/asterisk/bin/retrieve_conf(989): FreePBX\Cron->remove('* 1 * * * /usr/...')
#4 {main}

```
